### DISCUSSION TITLE
.clangd setup

### DISCUSSION THREAD

**Discussion by tenprint** [drmortalwombat/oscar64#67] [Q&A]
@drmortalwombat what setup do you use when writing your C64 programs?

I used VSCode and the following .clangd file in my project's root which is helping me to find the oscar64 library. It also suppresses one of the warnings. I added `use_of_tag_name_without_tag` to ignore the warning caused by using a struct like a type without an actual typedef. This helps, but it's not perfect.

```yaml
If:
  PathMatch: .*\.c

CompileFlags:
  Add: [-isystemC:\\Tools\\oscar64\\include]

Diagnostics:
  Suppress:
    - use_of_tag_name_without_tag
```

I'd like to turn on "format on save" but VSCode doesn't know how to handle things like PETSCII string annotations (e.g. p"Hello") or understand what #embed is so it mangles the code when it tries to format.

How might I provide VSCode and/or .clangd with information about oscar64 language additions so that the IDE doesn't incorrectly warn on things it doesn't understand?
